let numero1=12;
let numero2=6;
let soma=12+6;
let subtracao=12-6;
let divisao=12/6;
let multiplicacao=12*6;
console.log(soma);
console.log(subtracao);
console.log(divisao);
console.log(multiplicacao);